<?php

use Illuminate\Database\Seeder;

class ParkSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('parks')->truncate();  
        DB::table('parks')->insert([      
            [
                'code' => 'SSSC',
                'name' => 'Sesame Street Spaghetti Space Chase',
                'type' => 'rides',
                'opens_at' => '12:00',
                'closes_at' => '17:00',
                'intermission' => '0',
                'max_capacity' => '16',
                'start_to_end' => '300',
            ],
            [
                'code' => 'BGHVC',
                'name' => 'Battlestar Galactica: HUMAN vs. CYLON',
                'type' => 'rides',
                'opens_at' => '12:00',
                'closes_at' => '17:00',
                'intermission' => '0',
                'max_capacity' => '40',
                'start_to_end' => '120',
            ],
            [
                'code' => 'TTRTU3B',
                'name' => 'TRANSFORMERS The Ride: The Ultimate 3D Battle',
                'type' => 'rides',
                'opens_at' => '14:00',
                'closes_at' => '19:00',
                'intermission' => '0',
                'max_capacity' => '24',
                'start_to_end' => '240',
            ],
            [
                'code' => 'RM',
                'name' => 'Revenge of the Mummy',
                'type' => 'rides',
                'opens_at' => '12:00',
                'closes_at' => '17:00',
                'intermission' => '0',
                'max_capacity' => '12',
                'start_to_end' => '360',
            ],
            [
                'code' => 'MACA',
                'name' => 'Madagascar: A Crate Adventure',
                'type' => 'rides',
                'opens_at' => '12:00',
                'closes_at' => '17:00',
                'intermission' => '0',
                'max_capacity' => '16',
                'start_to_end' => '300',
            ],
            [
                'code' => 'PIBGJ',
                'name' => 'Puss In Boots’ Giant Journey',
                'type' => 'rides',
                'opens_at' => '13:00',
                'closes_at' => '18:00',
                'intermission' => '0',
                'max_capacity' => '22',
                'start_to_end' => '240',
            ],
            [
                'code' => 'TH',
                'name' => 'Treasure Hunters',
                'type' => 'rides',
                'opens_at' => '14:00',
                'closes_at' => '19:00',
                'intermission' => '0',
                'max_capacity' => '4',
                'start_to_end' => '160',
            ],
            [
                'code' => 'DL',
                'name' => 'Donkey Live',
                'type' => 'shows',
                'opens_at' => '12:00',
                'closes_at' => '17:00',
                'intermission' => '1800',
                'max_capacity' => '80',
                'start_to_end' => '900',
            ],
            [
                'code' => 'S4DA',
                'name' => 'Shrek 4-D Adventure',
                'type' => 'shows',
                'opens_at' => '12:00',
                'closes_at' => '17:00',
                'intermission' => '1800',
                'max_capacity' => '100',
                'start_to_end' => '1200',
            ],
            [
                'code' => 'WW',
                'name' => 'WaterWorld',
                'type' => 'shows',
                'opens_at' => '13:00',
                'closes_at' => '18:00',
                'intermission' => '1800',
                'max_capacity' => '50',
                'start_to_end' => '1500',
            ],
            [
                'code' => 'LCAHSS',
                'name' => 'Lights, Camera, Action!™ Hosted by Steven Spielberg',
                'type' => 'shows',
                'opens_at' => '14:00',
                'closes_at' => '19:00',
                'intermission' => '1800',
                'max_capacity' => '25',
                'start_to_end' => '1140',
            ],
            [
                'code' => 'ETT',
                'name' => 'Elmo’s TV Time',
                'type' => 'shows',
                'opens_at' => '13:00',
                'closes_at' => '18:00',
                'intermission' => '1800',
                'max_capacity' => '40',
                'start_to_end' => '1600',
            ],
            [
                'code' => 'LHS',
                'name' => 'Lake Hollywood Spectacular',
                'type' => 'shows',
                'opens_at' => '14:00',
                'closes_at' => '19:00',
                'intermission' => '18000',
                'max_capacity' => '200',
                'start_to_end' => '300',
            ],
            [
                'code' => 'TVC',
                'name' => 'Transformers: Voices of Cybertron',
                'type' => 'attractions',
                'opens_at' => '12:00',
                'closes_at' => '19:00',
                'intermission' => '3600',
                'max_capacity' => '300',
                'start_to_end' => '1800',
            ],
            [
                'code' => 'PBKS',
                'name' => 'Puss in Boots and Kitty Softpaws',
                'type' => 'attractions',
                'opens_at' => '12:00',
                'closes_at' => '19:00',
                'intermission' => '3600',
                'max_capacity' => '200',
                'start_to_end' => '1500',
            ],
            [
                'code' => 'M',
                'name' => 'Madagascar',
                'type' => 'attractions',
                'opens_at' => '14:00',
                'closes_at' => '20:00',
                'intermission' => '3600',
                'max_capacity' => '190',
                'start_to_end' => '1200',
            ],
            [
                'code' => 'SSSC',
                'name' => 'Gru and the Minions',
                'type' => 'attractions',
                'opens_at' => '13:00',
                'closes_at' => '19:00',
                'intermission' => '3600',
                'max_capacity' => '150',
                'start_to_end' => '900',
            ],
            [
                'code' => 'RE',
                'name' => 'Raptor Encounter',
                'type' => 'attractions',
                'opens_at' => '14:00',
                'closes_at' => '20:00',
                'intermission' => '3600',
                'max_capacity' => '100',
                'start_to_end' => '1000',
            ],
            [
                'code' => 'HWOF',
                'name' => 'Hollywood Walk Of Fame',
                'type' => 'attractions',
                'opens_at' => '12:00',
                'closes_at' => '19:00',
                'intermission' => '3600',
                'max_capacity' => '120',
                'start_to_end' => '850',
            ],
            [
                'code' => 'EA',
                'name' => 'Enchanted Airways',
                'type' => 'rides',
                'opens_at' => '12:00',
                'closes_at' => '17:00',
                'intermission' => '0',
                'max_capacity' => '24',
                'start_to_end' => '160',
            ]

        ]);
    }
}
